[package]
name = "go"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telegram = {path = "../telegram"}
reqwest = { version = "0.9.15", features=["rustls-tls"], default-features = false}
